apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v1
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - image: luksa/kubia:v1
          name: nodejs
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  type: NodePort
  selector:
    app: kubia
  ports:
    - port: 80         # Exposed service port
      targetPort: 8080  # Pod container's port
      nodePort: 30001   # Optional: You can specify the node port or let Kubernetes assign one

---
# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: kubia-v1
# spec:
#   replicas: 3
#   selector:
#     app: kubia
#   template:
#     metadata:
#       labels:
#         app: kubia
#     spec:
#       containers:
#         - image: luksa/kubia:v1
#           name: nodejs
#           ports:
#             - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kubia
# spec:
#   type: LoadBalancer
#   selector:
#     app: kubia
#   ports:
#     - port: 80
#       targetPort: 8080
